Trainer:
  TRAIN_LENGTH: 1000
  BATCH_SIZE: 20
  BUFFER_SIZE: 20
  STEPS_PER_EPOCH: 50
  OUTPUT_CHANNELS: 3
  EPOCHS: 100
  VAL_SUBSPLITS: 5
  VALIDATION_STEPS: 10

Dataset:
  CLASSES: 4
  HEIGHT: 256
  WIDTH: 256
  CHANNEL: 3
  FORMAT: RGB
  PREPROCESS: True
  NORMALIZATION: True
  DATA_PATH: "data"
